"""empty message

Revision ID: bc030a3b13b3
Revises: c1a3d64646a7
Create Date: 2016-04-27 16:13:20.074000

"""

# revision identifiers, used by Alembic.
revision = 'bc030a3b13b3'
down_revision = 'c1a3d64646a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('champion', sa.String(length=30), nullable=True))
    op.add_column('league', sa.Column('gameType', sa.String(length=30), nullable=True))
    op.add_column('league', sa.Column('leagueType', sa.String(length=30), nullable=True))
    op.add_column('league', sa.Column('matchType', sa.String(length=30), nullable=True))
    op.drop_column('league', 'team_quality')
    op.drop_column('league', 'regular_season')
    op.drop_column('league', 'playoff')
    op.drop_column('league', 'keeper_league')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('keeper_league', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('league', sa.Column('playoff', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('league', sa.Column('regular_season', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('league', sa.Column('team_quality', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('league', 'matchType')
    op.drop_column('league', 'leagueType')
    op.drop_column('league', 'gameType')
    op.drop_column('league', 'champion')
    ### end Alembic commands ###
